### ISSUE TITLE
Bug in Eventclient

### ISSUE THREAD

**Issue by bararchy** [PredictionIO/PredictionIO-Ruby-SDK#7]
Hi, 

There is a bug in this File\Line 
https://github.com/PredictionIO/PredictionIO-Ruby-SDK/blob/develop/lib/predictionio/event_client.rb#L86

an Unneeded URI, or needed but undefined.
removing it allows the use of this gem.

**Comment by EmergentOrder** [comment]
There's a missing require here, added it, URI works now. Fixed in [PR #9](https://github.com/PredictionIO/PredictionIO-Ruby-SDK/pull/9 ) and merged to develop
